[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Single Page App routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

# (Future) If/when we add Netlify Functions for GraphQL
#[functions]
#  directory = "netlify/functions"
